language: go

go:
  - 1.12.x
  - 1.11.x

env:
  - GO111MODULE=on

before_install:
  - go get 

script:
  - cd cmd/secret
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)