version: '3'

services:
  redis:
    image: redis:alpine
    # command: ["redis-server", "--appendonly", "yes"]
    # container_name: cache
    # expose:
    #   - "5432"

  secret:
    build: 
      dockerfile:  deployments/docker/secret/Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    # links:
    # - redis
    depends_on:
      - redis