version: '3'

services:
  redis:
    image: redis:alpine
    expose: 
      - 6379

  secret:
    build: 
      context: .
    container_name: secret
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      GIN_MODE: release
    depends_on:
      - redis
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./configurations/prometheus:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - secret
    expose:
      - 9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      # - ./volumes/grafana:/var/lib/grafana
      - ./configurations/grafana/provisioning/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./configurations/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    links:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always