global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'secret'
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets: ['secret-web.herokuapp.com']
