{
 "title": "Secret server",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "GET Secret Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "secret_request_processing_time_summary_ms{endpoint=\"secret_get\",quantile=\"0.5\"}",
     "legendFormat": "Quantille 50%"
    },
    {
     "expr": "secret_request_processing_time_summary_ms{endpoint=\"secret_get\",quantile=\"0.95\"}",
     "legendFormat": "Quantille 95%"
    },
    {
     "expr": "secret_request_processing_time_summary_ms{endpoint=\"secret_get\",quantile=\"0.99\"}",
     "legendFormat": "Quantille 99%"
    }
   ]
  },
  {
   "title": "POST Secret Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "secret_request_processing_time_summary_ms{endpoint=\"secret_post\",quantile=\"0.5\"}",
     "legendFormat": "Quantille 50%"
    },
    {
     "expr": "secret_request_processing_time_summary_ms{endpoint=\"secret_post\",quantile=\"0.95\"}",
     "legendFormat": "Quantille 95%"
    },
    {
     "expr": "secret_request_processing_time_summary_ms{endpoint=\"secret_post\",quantile=\"0.99\"}",
     "legendFormat": "Quantille 99%"
    }
   ]
  },
  {
   "title": "Request count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "secret_request_number{endpoint=\"secret_get\"}",
     "legendFormat": "GET Secret"
    },
    {
     "expr": "secret_request_number{endpoint=\"secret_post\"}",
     "legendFormat": "POST Secret"
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0\"}",
     "legendFormat": "Quantille 0%"
    },
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.25\"}",
     "legendFormat": "Quantille 25%"
    },
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "Quantille 50%"
    },
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.75\"}",
     "legendFormat": "Quantille 75%"
    },
    {
     "expr": "go_gc_duration_seconds{quantile=\"1\"}",
     "legendFormat": "Quantille 100%"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "Allocated memory (bytes)" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "Goroutines" }
   ]
  }
 ]
}